### PR TITLE
Include multiple client conclusion

### PR DESCRIPTION
**Pull request by fryorcraken**
- go-waku only focuses on status-go
- bindings step to expose new protocol on binding API
- docs should include protocol explanation

### CODE REVIEW

**Comment by fryorcraken** [comment]
Note that we should support in go-waku whatever is needed by Graphcast team until we are able to swap to nwaku.

**Comment by danisharora099** [comment]
> Note that we should support in go-waku whatever is needed by Graphcast team until we are able to swap to nwaku.

does this affect maintaining interop tests between clients? 
clients should continue to support interop testing with go-waku as before, right?

**Comment by chaitanyaprem** [comment]
> > Note that we should support in go-waku whatever is needed by Graphcast team until we are able to swap to nwaku.
> 
> does this affect maintaining interop tests between clients? clients should continue to support interop testing with go-waku as before, right?

Interop tests where go-waku is used as a client or SDK (for light protocols or relay) can still continue. But tests where go-waku is being used as a serviceNode need not be continued IIUC.

**Comment by danisharora099** [comment]
> > > Note that we should support in go-waku whatever is needed by Graphcast team until we are able to swap to nwaku.
> > 
> > 
> > does this affect maintaining interop tests between clients? clients should continue to support interop testing with go-waku as before, right?
> 
> Interop tests where go-waku is used as a client or SDK (for light protocols or relay) can still continue. But tests where go-waku is being used as a serviceNode need not be continued IIUC.

at least for the context of js-waku, interop with go-waku was being done with go-waku seen as a service node and js-waku being a client. along with stopping further maintenance (and removing CI workflow for it), perhaps removing interop tests altogether might be an idea?

**Comment by richard-ramos** [comment]
> perhaps removing interop tests altogether might be an idea?

I'd vote for removing integration tests between js-waku and go-waku, and even go as far as removing the service node functionality from go-waku itself

**Comment by fryorcraken** [comment]
> > perhaps removing interop tests altogether might be an idea?
> 
> I'd vote for removing integration tests between js-waku and go-waku, and even go as far as removing the service node functionality from go-waku itself

I agree with that on principle but I'd like the dust to settle on this decision first.

Fine to disable for now and we can fully remove it after offsite.

**Pull request merged**
